version: 2
updates:
  - package-ecosystem: pip
    directory: /hmpd/app
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /hmpd
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
