name: HMPD Thermostat Bridge
slug: hmpd
version: "4.1.1"
description: Expose HMPD thermostat zones to Home Assistant as MQTT climate entities
arch:
  - amd64
  - aarch64

startup: services
boot: auto
init: false
uart: true

map:
  - type: homeassistant_config
    path: /homeassistant
  - type: addon_config
    read_only: false
    path: /config

options:
  debug: false
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  hmpd_path: /app/hmpd
  controllers:
    - name: usb0
      dev: /dev/ttyUSB0
      baud: 4800
      expected_regs: 64
    - name: usb1
      dev: /dev/ttyUSB1
      baud: 4800
      expected_regs: 39

schema:
  debug: bool
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  hmpd_path: str
  controllers:
    - name: str
      dev: str
      baud: int(1,)
      expected_regs: int(1,)
