name: HMPD Thermostat Bridge
slug: hmpd
version: "1.1.7"
description: Expose HMPD thermostat zones to Home Assistant as MQTT climate entities
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
uart: true
map:
  - type: homeassistant_config
    read_only: true
    path: /homeassistant
  - type: addon_config
    read_only: false
    path: /config
